import { LogCategory } from '/@/renderer/utils/logger';

export const logMsg = {
    [LogCategory.ANALYTICS]: {
        appTracked: 'App tracked',
        pageViewTracked: 'Page view tracked',
    },
    [LogCategory.API]: {},
    [LogCategory.EXTERNAL]: {
        discordRpcActivityCleared: 'Activity was cleared for Discord RPC',
        discordRpcInitialized: 'Discord RPC was initialized',
        discordRpcQuit: 'Discord RPC was quit',
        discordRpcSetActivity: 'Activity was set for Discord RPC',
        discordRpcTrackChanged: 'Track was changed for Discord RPC',
        discordRpcUpdateSkipped: 'Activity was not updated for Discord RPC',
    },
    [LogCategory.OTHER]: {
        error: 'An error occurred',
        warning: 'A warning occurred',
    },
    [LogCategory.PLAYER]: {
        addToQueueByData: 'Added to queue by data',
        addToQueueByFetch: 'Added to queue by fetch',
        addToQueueByListQuery: 'Added to queue by list query',
        addToQueueByType: 'Added to queue by type',
        autoPlayFailed: 'Auto play failed',
        autoPlayTriggered: 'Auto play triggered',
        cancelledFetch: 'Cancelled fetch',
        clearQueue: 'Cleared queue',
        clearSelected: 'Cleared selected',
        decreaseVolume: 'Decreased volume',
        increaseVolume: 'Increased volume',
        mediaNext: 'Media next',
        mediaPause: 'Media pause',
        mediaPlay: 'Media play',
        mediaPlayByIndex: 'Media play by index',
        mediaPrevious: 'Media previous',
        mediaSeekToTimestamp: 'Media seek to timestamp',
        mediaSkipBackward: 'Media skip backward',
        mediaSkipForward: 'Media skip forward',
        mediaStop: 'Media stop',
        mediaToggleMute: 'Media toggle mute',
        mediaTogglePlayPause: 'Media toggle play pause',
        moveSelectedTo: 'Moved selected to',
        moveSelectedToBottom: 'Moved selected to bottom',
        moveSelectedToNext: 'Moved selected to next',
        moveSelectedToTop: 'Moved selected to top',
        playbackError: 'An error occurred during playback',
        playerFiltersApplied: 'Player filters applied',
        setFavorite: 'Set favorite',
        setQueue: 'Set queue',
        setRating: 'Set rating',
        setRepeat: 'Set repeat',
        setShuffle: 'Set shuffle',
        setSpeed: 'Set speed',
        setVolume: 'Set volume',
        shuffle: 'Shuffle',
        shuffleAll: 'Shuffle all',
        shuffleSelected: 'Shuffle selected',
        toggleRepeat: 'Toggle repeat',
        toggleShuffle: 'Toggle shuffle',
    },
    [LogCategory.SCROBBLE]: {
        scrobbledPause: 'Scrobbled a pause event',
        scrobbledStart: 'Scrobbled a start event',
        scrobbledSubmission: 'Scrobbled a submission event',
        scrobbledTimeupdate: 'Scrobbled a timeupdate event',
        scrobbledUnpause: 'Scrobbled an unpause event',
    },
    [LogCategory.SYSTEM]: {
        authenticatingServer: 'Authenticating server',
        serverAuthenticationAborted: 'Server authentication aborted',
        serverAuthenticationError: 'Server authentication error',
        serverAuthenticationFailed: 'Server authentication failed',
        serverAuthenticationInvalid: 'Server authentication invalid',
        serverAuthenticationSuccess: 'Server authentication successful',
    },
};
