allowBuilds:
    abstract-socket: true
    electron: true
    electron-winstaller: true
    esbuild: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    - 'taglib-wasm@1.5.1'
overrides:
    'xml2js': '0.5.0'
    'react-router': '7.14.0'
