declare global {
    interface Window {
        ANALYTICS_DISABLED?: boolean | string;
        FS_AUTO_DJ_ENABLED?: string;
        FS_AUTO_DJ_ITEM_COUNT?: string;
        FS_AUTO_DJ_TIMING?: string;
        FS_CSS_CONTENT?: string;
        FS_CSS_ENABLED?: string;
        FS_DISCORD_CLIENT_ID?: string;
        FS_DISCORD_DISPLAY_TYPE?: string;
        FS_DISCORD_ENABLED?: string;
        FS_DISCORD_LINK_TYPE?: string;
        FS_DISCORD_SHOW_AS_LISTENING?: string;
        FS_DISCORD_SHOW_PAUSED?: string;
        FS_DISCORD_SHOW_SERVER_IMAGE?: string;
        FS_DISCORD_SHOW_STATE_ICON?: string;
        FS_FONT_BUILT_IN?: string;
        FS_FONT_SYSTEM?: string;
        FS_FONT_TYPE?: string;
        FS_GENERAL_ACCENT?: string;
        FS_GENERAL_ALBUM_BACKGROUND?: string;
        FS_GENERAL_ALBUM_BACKGROUND_BLUR?: string;
        FS_GENERAL_ARTIST_BACKGROUND?: string;
        FS_GENERAL_ARTIST_BACKGROUND_BLUR?: string;
        FS_GENERAL_BLUR_EXPLICIT_IMAGES?: string;
        FS_GENERAL_COMBINED_LYRICS_AND_VISUALIZER?: string;
        FS_GENERAL_ENABLE_GRID_MULTI_SELECT?: string;
        FS_GENERAL_EXTERNAL_LINKS?: string;
        FS_GENERAL_FOLLOW_CURRENT_SONG?: string;
        FS_GENERAL_FOLLOW_SYSTEM_THEME?: string;
        FS_GENERAL_HOME_FEATURE?: string;
        FS_GENERAL_HOME_FEATURE_STYLE?: string;
        FS_GENERAL_LANGUAGE?: string;
        FS_GENERAL_LAST_FM?: string;
        FS_GENERAL_LASTFM_API_KEY?: string;
        FS_GENERAL_MUSIC_BRAINZ?: string;
        FS_GENERAL_NATIVE_ASPECT_RATIO?: string;
        FS_GENERAL_PATH_REPLACE?: string;
        FS_GENERAL_PATH_REPLACE_WITH?: string;
        FS_GENERAL_PLAYERBAR_OPEN_DRAWER?: string;
        FS_GENERAL_PRIMARY_SHADE?: string;
        FS_GENERAL_RESUME?: string;
        FS_GENERAL_SHOW_LYRICS_IN_SIDEBAR?: string;
        FS_GENERAL_SHOW_RATINGS?: string;
        FS_GENERAL_SHOW_VISUALIZER_IN_SIDEBAR?: string;
        FS_GENERAL_SIDE_QUEUE_TYPE?: string;
        FS_GENERAL_SIDEBAR_COLLAPSE_SHARED?: string;
        FS_GENERAL_SIDEBAR_COLLAPSED_NAVIGATION?: string;
        FS_GENERAL_SIDEBAR_PLAYLIST_LIST?: string;
        FS_GENERAL_SIDEBAR_PLAYLIST_SORTING?: string;
        FS_GENERAL_THEME?: string;
        FS_GENERAL_THEME_DARK?: string;
        FS_GENERAL_THEME_LIGHT?: string;
        FS_GENERAL_USE_THEME_ACCENT_COLOR?: string;
        FS_GENERAL_USE_THEME_PRIMARY_SHADE?: string;
        FS_GENERAL_ZOOM_FACTOR?: string;
        FS_LYRICS_ALIGNMENT?: string;
        FS_LYRICS_DELAY_MS?: string;
        FS_LYRICS_ENABLE_AUTO_TRANSLATION?: string;
        FS_LYRICS_FETCH?: string;
        FS_LYRICS_FOLLOW?: string;
        FS_LYRICS_PREFER_LOCAL?: string;
        FS_LYRICS_SHOW_MATCH?: string;
        FS_LYRICS_SHOW_PROVIDER?: string;
        FS_LYRICS_TRANSLATION_API_KEY?: string;
        FS_LYRICS_TRANSLATION_TARGET_LANGUAGE?: string;
        FS_PLAYBACK_AUDIO_FADE_ON_STATUS_CHANGE?: string;
        FS_PLAYBACK_MEDIA_SESSION?: string;
        FS_PLAYBACK_PRESERVE_PITCH?: string;
        FS_PLAYBACK_SCROBBLE_AT_DURATION?: string;
        FS_PLAYBACK_SCROBBLE_AT_PERCENTAGE?: string;
        FS_PLAYBACK_SCROBBLE_ENABLED?: string;
        FS_PLAYBACK_SCROBBLE_NOTIFY?: string;
        FS_PLAYBACK_TRANSCODE_ENABLED?: string;
        FS_PLAYBACK_WEB_AUDIO?: string;
        LEGACY_AUTHENTICATION?: boolean | string;
        REMOTE_URL?: string;
        SERVER_LOCK?: boolean | string;
        SERVER_NAME?: string;
        SERVER_TYPE?: string;
        SERVER_URL?: string;
        umami?: {
            identify(unique_id: string): void;
            identify(unique_id: string, data: object): void;
            identify(data: object): void;
            track(): void;
            track(event_name: string, data: object): void;
            track(
                callback: (props: {
                    hostname: string;
                    language: string;
                    referrer: string;
                    screen: string;
                    title: string;
                    url: string;
                    website: string;
                }) => object,
            ): void;
        };
    }
}

export {};
